services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE  # データベース名を環境変数から設定
    ports:
      - "3306:3306"
    volumes:
      - "./api/tmp/db:/var/lib/mysql"

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      RAILS_ENV: development  # Railsの環境変数を設定
      BUNDLE_DEPLOYMENT: "0"
    volumes:
      - "./api:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"
    command: bash -c "bundle config unset frozen && bundle install && rm -rf /usr/local/bundle/bundler/gems/*/.git && bundle exec bootsnap precompile --gemfile && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  front:
    build:
      context: front/
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./front:/app
    command: yarn dev
    ports:
      - "4001:3000"
